#!/bin/sh
### BEGIN INIT INFO
# Provides:          robotics-controller
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Robotics Controller Service
# Description:       Main robotics controller application
### END INIT INFO

# Source function library
. /etc/init.d/functions

USER="root"
DAEMON="robotics-controller"
ROOT_DIR="/usr/bin"

PIDFILE="/var/run/robotics-controller.pid"
LOCKFILE="/var/lock/subsys/robotics-controller"

start() {
    if [ -f $PIDFILE ]; then
        echo "$DAEMON is already running"
        return 1
    fi
    
    echo -n "Starting $DAEMON: "
    daemon --user "$USER" --pidfile="$PIDFILE" "$ROOT_DIR/$DAEMON"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    return $RETVAL
}

stop() {
    echo -n "Shutting down $DAEMON: "
    pid=$(ps -aefw | grep "$DAEMON" | grep -v " grep " | awk '{print $2}')
    kill -9 $pid > /dev/null 2>&1
    [ $? -eq 0 ] && echo "OK" || echo "FAIL"
    rm -f $PIDFILE
    rm -f $LOCKFILE
}

status() {
    if [ -f $PIDFILE ]; then
        echo "$DAEMON is running"
    else
        echo "$DAEMON is stopped"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac

exit $?
